backend:
  name: git-gateway
  branch: main
site_url: https://weibiomed.com

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "首頁內容"
    folder: "content/home"
    create: true
    slug: "index"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "介紹", name: "intro", widget: "text" }
      - { label: "內容", name: "body", widget: "markdown" }

  - name: "about"
    label: "關於我們"
    folder: "content/about"
    create: false
    slug: "index"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "介紹", name: "intro", widget: "text" }
      - { label: "內容", name: "body", widget: "markdown" }

  - name: "news"
    label: "最新消息"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "介紹", name: "intro", widget: "text" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "內容", name: "body", widget: "markdown" }

  - name: "services"
    label: "產品與服務"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "介紹", name: "intro", widget: "text" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "內容", name: "body", widget: "markdown" }