backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "首頁"
    folder: "content/home"
    create: true
    slug: "index"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "介紹段落", name: "intro", widget: "text" }

  - name: "about"
    label: "關於我們"
    folder: "content/about"
    create: true
    slug: "about"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "內容", name: "body", widget: "markdown" }

  - name: "contact"
    label: "聯絡資訊"
    folder: "content/contact"
    create: true
    slug: "contact"
    fields:
      - { label: "Email", name: "email", widget: "string" }
      - { label: "電話", name: "phone", widget: "string" }
      - { label: "地址", name: "address", widget: "text" }